version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - "jenkins_home:/var/jenkins/home"
    networks:
      - jenkins_network
networks:
  jenkins_network:
volumes:
  jenkins_home:
